# Generated by Django 2.1.7 on 2019-04-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_slide_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='monitor',
            field=models.CharField(choices=[('First Floor Lobby', 'First Floor Lobby'), ('Second Floor Lobby', 'Second Floor Lobby'), ('Second Floor Office', 'Second Floor Office')], default='', max_length=256),
        ),
        migrations.AddField(
            model_name='slide',
            name='priority',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='department',
            name='role',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('approve', 1), ('reject', 2), ('pending', 0)], default=0, max_length=2),
        ),
    ]
