# Generated by Django 2.1.7 on 2019-04-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190408_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='slide',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default=0, max_length=20),
        ),
    ]
