# Generated by Django 2.1.7 on 2019-04-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190408_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slide',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='monitor',
            field=models.CharField(choices=[('First Floor Lobby', 'First Floor Lobby'), ('Second Floor Lobby', 'Second Floor Lobby'), ('Second Floor Office', 'Second Floor Office')], default='First Floor Lobby', max_length=256),
        ),
        migrations.AlterField(
            model_name='slide',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
