# Generated by Django 2.1.7 on 2019-04-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_slide_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='file',
            field=models.FileField(default=True, upload_to='slides'),
        ),
    ]
