# Generated by Django 2.1.7 on 2019-04-10 01:11

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190409_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='file',
            field=models.FileField(default='', upload_to=homepage.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('approve', 'approved'), ('reject', 'rejected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
