# Generated by Django 2.1.7 on 2019-04-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190409_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('approved', 'approve'), ('rejected', 'rejecte'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
