# Generated by Django 2.1.7 on 2019-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20190409_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
