# Generated by Django 2.1.7 on 2019-04-24 23:24

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20190410_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='reject_info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='role',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='slide',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=homepage.models.get_file_path),
        ),
    ]
